### PR TITLE
Create a generic Python lint and test workflow.

### PR DESCRIPTION
**Pull request by beauremus**
This is meant to address #59.

### CODE REVIEW

**Comment by beauremus** [comment]
By the way, I should note that I noticed that the linting doesn't inhibit the build. I think we should decide if that's something we want. Maybe we need to choose which kind of lining issue prevents a build.

**Review by rneswold — COMMENTED** [review]
I'm not familiar enough with Actions to know if this will work. However, I like we're testing against these versions of Python. I think the build needs to test installing the `gssapi` dependency.

**Comment by beauremus** [comment]
What should the goal of testing `gssapi` be? Should we build against each of the available OSs? Should we invent a cross-compilation step for non-x86 architectures?
Maybe we should consider bundling a pre-built `gssapi` module into our distribution?

**Comment by rneswold** [comment]
I'd like to feel confident that users can build with `gssapi`. But I don't know that we can guarantee it -- even if it builds correctly in Actions so maybe this is a unrealizable goal.

**Comment by beauremus** [comment]
We should probably make another issue for building `gssapi` since it will be a significant effort.
This tool looks promising, https://github.com/pypa/cibuildwheel.
Let's approve this PR and get it published.
I'm game to talk you through the workflow if that feels useful.

**Review by rneswold — APPROVED** [review]
This looks good. We'll save the `gssapi` effort for another issue.

**Pull request merged**
