### PR TITLE
Use snake_case method names and deprecate the camelCase names

### PR DESCRIPTION
**Pull request by beauremus**
The Python convention for variable naming is snake_case with the exception of class names, which are camelCase. Here we create snake_case versions of previously camelCase functions and apply deprecation warnings to the camelCase versions.

This is meant to address #58.

### CODE REVIEW

**Comment by beauremus** [comment]
#62 goes further and makes the non-user-facing variables snake_case as well.

**Comment by beauremus** [comment]
This PR should be ready with the commits from the previous PR. I want to know if you think the deprecation strategy is sufficient. I followed the book for this. These won't appear to users; only in developer mode will these warnings appear.

**Review by rneswold — COMMENTED** [review]
Hmmm. Those warnings mean a script is going to send out a torrent of messages until they update their script. Is this what we want?

**Comment by beauremus** [comment]
The `DeprecationWarning` is only meant for developers. It is ignored by default unless someone enables developer mode.
https://docs.python.org/3/library/exceptions.html#DeprecationWarning

**Review by rneswold — APPROVED** [review]
Looks good.

**Pull request merged**
